### ISSUE TITLE
Clever package name?

### ISSUE THREAD

**Issue by jchodera** [choderalab/mtenn#2]
MTENN is a great start, but I wonder if we can come up with a more clever name for this package.

Some ideas:
* Structure Informed Deep Equivariant Compound Affinity Regressor ([SIDECAR](https://www.thespruceeats.com/classic-sidecar-cocktail-recipe-760601))
* Neural Equivariant Graph Regression of Novel Ideations ([NEGRONI](https://www.thespruceeats.com/negroni-cocktail-recipe-759327))
* Structure-based Learned Inference of Novel Graphs ([SLING](https://www.thespruceeats.com/singapore-sling-recipe-760602))

**Comment by yuanqing-wang** [comment]
I was just about to raise this issue when I saw you've beaten me to it, @jchodera 

I was gonna call it **S**tructrual **A**naly**Z**er with **E**quivariance for **R**apid **A**ffinity **C**omputation.

but on a second thought it's not half as elegant as SIDECAR. 

Let's leave this to @kaminow to decide

**Comment by hmacdope** [comment]
I am about to cut a 0.1.0 release for @kaminow so that we can push ahead on some integration into `asapdiscovery`. @jchodera @yuanqing-wang @kaminow if you would like to change the name it would probably be best to do it before I make any tags.

**Comment by hmacdope** [comment]
From talking with @kaminow  and no immediate complaints I will close this issue and proceed to cutting a release. If people change their mind just re-open and I will sort it out.
